spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  tracing:
    sampling:
      probability: 1.0

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, prometheus
#  endpoint:
#    loggers:
#      enabled: false
#  tracing:
#    sampling:
#      probability: 1.0
#  metrics:
#    tags:
#      application: springboot-3
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

